services:
  web:
    build:
      context: .
      target: test
    image: ${FILECHECK_IMAGE:-perma-filecheck}
    volumes:
      - ./main.py:/app/main.py:ro
      - ./test_main.py:/app/test_main.py:ro
      - ./test_assets:/app/test_assets:ro
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - DOCKERIZED=True
    extra_hosts:
      - "filecheck.perma.test:127.0.0.1"
    cap_add:
      - SYS_PTRACE
