services:
  web:
    build:
      context: .
    image: perma-filecheck
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - DOCKERIZED=True
    extra_hosts:
      - "filecheck.perma.test:127.0.0.1"
    cap_add:
      - SYS_PTRACE
