[project]
name = "perma-filecheck"
version = "0.1.0"
description = "Microservice for validating and scanning uploaded files"
license = "GPL-3.0-or-later"
requires-python = ">=3.13,<4"
dependencies = [
    "fastapi==0.136.1",
    "filetype==1.2.0",
    "lil-request-logging",
    "python-dateutil==2.9.0.post0",
    "python-multipart==0.0.30",
    "uvicorn==0.46.0",
]

[dependency-groups]
dev = [
    "flake8==7.3.0",
    "httpx==0.28.1",
    "pytest==9.1.1",
    "pytest-cov==7.1.0",
]

[tool.pytest.ini_options]
addopts = "--cov-report term-missing --cov --cov-fail-under=100"

[tool.uv.sources]
lil-request-logging = { url = "https://github.com/harvard-lil/lil-request-logging/releases/download/v0.1.0/lil_request_logging-0.1.0-py3-none-any.whl" }
