name: Tests

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.0

      - name: Run tests
        shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"'
        run: |
          docker compose down --remove-orphans
          docker compose build --pull
          docker compose up -d
          sleep 25

          docker ps
          docker compose exec web clamdscan --version
          docker compose exec web python -m pip install pytest pytest-cov
          docker compose exec web python -m pytest